export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';


export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_LESSONS = 'FETCH_LESSONS';
export const FETCH_LESSONS_GROUPS = 'FETCH_LESSONS_GROUPS';


// Create new lesson
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS';
export const CREATE_LESSON_FAILURE = 'CREATE_LESSON_FAILURE';
export const EDIT_LESSON_SUCCESS = 'EDIT_LESSON_SUCCESS';
export const EDIT_LESSON_FAILURE = 'EDIT_LESSON_FAILURE';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
export const DELETE_LESSON_FAILURE = 'DELETE_LESSON_FAILURE';
export const RESET_NEW_LESSON = 'RESET_NEW_LESSON';

// Lesson Groups
export const CREATE_LESSON_GROUP_SUCCESS = 'CREATE_LESSON_GROUPS_SUCCESS';
export const CREATE_LESSON_GROUP_FAILURE = 'CREATE_LESSON_GROUPS_FAILURE';
